[versions]
java = "11"
kotlin = "1.8.0"
pluginPublish = "1.0.0"
kotest = "5.4.0"
buildconfig = "3.1.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
docusaurusOssTemplate = { id = "co.touchlab.touchlabtools.docusaurusosstemplate", version = "0.1.9" }

[libraries]
plugin-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-gradle-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
plugin-buildconfig = { module = "com.github.gmazzo:gradle-buildconfig-plugin", version.ref = "buildconfig" }
plugin-pluginPublish = { module = "com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin", version.ref = "pluginPublish" }

kotlin-native-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-native-compiler-embeddable", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.4.0" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }
swiftPoet = { module = "co.touchlab.fork.swiftpoet:swiftpoet", version = "1.5.0-touchlab" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.12.0" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version = "1.12.5" }

[bundles]
testing-jvm = [
    "kotlin-test",
    "kotest-runner-junit5",
    "kotest-assertions-core",
    "kotest-framework-datatest",
    "mockk"
]
