name: "[Broken] Compare Pure and SKIE"

on:
  workflow_dispatch:
    inputs:
      onlyIndices:
        description: 'Only run tests for the given indices (comma-separated)'
        required: false
        type: string
        default: ''

permissions:
  contents: read
  checks: write

jobs:
  run-comparison:
    name: Compare Pure and SKIE
    concurrency: ci-compare-tests-${{ github.ref }}
    timeout-minutes: 600
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Prepare Worker
        uses: ./.github/actions/prepare-worker
      - name: Run External Libraries Tests
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: ':acceptance-tests:external-libraries:test :acceptance-tests:external-libraries:pureTest :acceptance-tests:external-libraries:comparePureAndSkie --continue'
        env:
          onlyIndices: ${{ github.event.inputs.onlyIndices }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          DISABLE_PARALLEL_TESTS: true
          KOTLIN_STATIC_FRAMEWORK: true
          KOTLIN_BUILD_CONFIGURATION: release
      - name: Upload Comparison Report (S3)
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TOUCHLAB_DEPLOY_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TOUCHLAB_DEPLOY_PRIVATE }}
        run: |
          aws s3 sync acceptance-tests/external-libraries/build/reports/comparison s3://skie-data/comparison-reports
      - name: Upload Comparison Report (GitHub artifact)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: 'Comparison Report'
          path: 'acceptance-tests/external-libraries/build/reports/comparison/*.csv'
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: "Comparison Report"
          report_paths: 'acceptance-tests/external-libraries/build/test-results/comparePureAndSkie/TEST-*.xml'
          require_tests: true
          include_passed: true
          update_check: true
          annotate_only: true
          detailed_summary: true
