name: Smoke Tests [New]

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  checks: write

jobs:
  smoke-tests:
    name: Smoke Tests
    runs-on: self-hosted
    steps:
      - uses: touchlab/SKIE@tk/smoke-tests
        with:
          github-token: ${{ secrets.ACCEPTANCE_TESTS_TOKEN }}
    