name: Smoke Tests 1.8.20

on:
  workflow_dispatch:
    inputs:
      linkage:
        type: choice
        options:
          - static
          - dynamic
        required: true
        default: static
        description:
          'The linkage mode to use for the tests. "static" will produce static frameworks, "dynamic" will produce dynamic frameworks.'
      configuration:
        type: choice
        options:
          - debug
          - release
        required: true
        default: debug
        description:
          'The configuration to use for the tests. "release" will produce release builds, "debug" will produce debug builds (type mapping tests currently always use release).'
      target:
        type: choice
        options:
          - ios_arm64
          - ios_x64
          - ios_simulator_arm64
          - macos_arm64
          - macos_x64
        required: true
        default: macos_arm64
        description:
          'The target to use for the type mapping tests.'

permissions:
  contents: read
  checks: write

jobs:
  acceptance-tests:
    name: Acceptance Tests
    runs-on: macos-14
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCEPTANCE_TESTS_TOKEN }}
      - name: Prepare Worker
        uses: ./.github/actions/prepare-worker
      - name: Run Acceptance Tests
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: ':acceptance-tests:functional__kgp_1.8.20Test'
          build-root-directory: SKIE
        env:
          KOTLIN_LINK_MODE: ${{ inputs.linkage }}
          KOTLIN_BUILD_CONFIGURATION: ${{ inputs.configuration }}

  type-mapping-tests:
    name: Type Mapping Tests
    runs-on: macos-14
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCEPTANCE_TESTS_TOKEN }}
      - name: Prepare Worker
        uses: ./.github/actions/prepare-worker
      - name: Run Type Mapping Tests
        uses: gradle/gradle-build-action@v2.4.2
        id: run-tests
        with:
          arguments: ':acceptance-tests:type-mapping__kgp_1.8.20Test'
          build-root-directory: SKIE
        env:
          KOTLIN_LINK_MODE: ${{ inputs.linkage }}
          KOTLIN_TARGET: ${{ inputs.target }}
          KOTLIN_BUILD_CONFIGURATION: ${{ inputs.configuration }}

  external-libraries-tests:
    name: External Libraries Tests
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCEPTANCE_TESTS_TOKEN }}
      - name: Prepare Worker
        uses: ./.github/actions/prepare-worker
      - name: Run External Libraries Tests
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: ':acceptance-tests:libraries__kgp_1.8.20Test'
          build-root-directory: SKIE
        env:
          KOTLIN_LINK_MODE: ${{ inputs.linkage }}
          KOTLIN_BUILD_CONFIGURATION: ${{ inputs.configuration }}
