name: Smoke Tests All versions

on:
  schedule:
#     Every Saturday at 2am EST
    - cron: '0 7 * * SAT'
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  checks: write

concurrency:
  group: ci-smoke-tests-all

jobs:
  acceptance-tests:
    name: Acceptance Tests
    runs-on: self-hosted
    strategy:
      matrix:
        version: [ "2.0.0", "2.0.20", "2.1.0", "2.1.20", "2.2.0" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCEPTANCE_TESTS_TOKEN }}
      - name: Prepare Worker
        uses: ./.github/actions/prepare-worker
      - name: Run Acceptance Tests
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: ':acceptance-tests:functional:kgp_${{ matrix.version }}Test'
          build-root-directory: SKIE
        env:
          KOTLIN_LINK_MODE: static
          KOTLIN_BUILD_CONFIGURATION: debug

  type-mapping-tests:
    name: Type Mapping Tests
    runs-on: self-hosted
    strategy:
      matrix:
        version: [ "2.0.0", "2.0.20", "2.1.0", "2.1.20", "2.2.0" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCEPTANCE_TESTS_TOKEN }}
      - name: Prepare Worker
        uses: ./.github/actions/prepare-worker
      - name: Run Type Mapping Tests
        uses: gradle/gradle-build-action@v2.4.2
        id: run-tests
        with:
          arguments: ':acceptance-tests:type-mapping:kgp_${{ matrix.version }}Test'
          build-root-directory: SKIE
        env:
          KOTLIN_LINK_MODE: static
          KOTLIN_TARGET: macos_arm64
          KOTLIN_BUILD_CONFIGURATION: debug

  external-libraries-tests:
    name: External Libraries Tests
    runs-on: self-hosted
    strategy:
      matrix:
        version: [ "2.0.0", "2.0.20", "2.1.0", "2.1.20", "2.2.0" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCEPTANCE_TESTS_TOKEN }}
      - name: Prepare Worker
        uses: ./.github/actions/prepare-worker
      - name: Run External Libraries Tests
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: ':acceptance-tests:libraries:kgp_${{ matrix.version }}Test'
          build-root-directory: SKIE
        env:
          KOTLIN_LINK_MODE: static
          KOTLIN_BUILD_CONFIGURATION: debug

  gradle-tests:
    name: Gradle Tests
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCEPTANCE_TESTS_TOKEN }}
      - name: Prepare Worker
        uses: ./.github/actions/prepare-worker
      - name: Run Gradle Tests
        uses: gradle/gradle-build-action@v2.4.2
        id: run-tests
        with:
          arguments: >-
            :test
            -PtestLevel=smoke
            -PtestType=gradle
            "-Pmatrix.targets=macosArm64"
            "-Pmatrix.configurations=debug"
            "-Pmatrix.linkModes=static"
          build-root-directory: test-runner
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: ${{ failure() || success() }}
        with:
          check_name: "Smoke Test Reports - Gradle Tests"
          report_paths: 'test-runner/build/test-results/test/TEST-*.xml'
          require_tests: true
